[package]
name = "tease"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartcore = "0.2.1"
wry = "0.18.2"
human_regex = "0.2.3"